// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayType int32

const (
	PayType_WECHAT   PayType = 0
	PayType_ALIPAY   PayType = 1
	PayType_UNIONPAY PayType = 2
)

var PayType_name = map[int32]string{
	0: "WECHAT",
	1: "ALIPAY",
	2: "UNIONPAY",
}

var PayType_value = map[string]int32{
	"WECHAT":   0,
	"ALIPAY":   1,
	"UNIONPAY": 2,
}

func (x PayType) String() string {
	return proto.EnumName(PayType_name, int32(x))
}

type PayStatus int32

const (
	PayStatus_PENDING    PayStatus = 0
	PayStatus_SUCCESS    PayStatus = 1
	PayStatus_FAILED     PayStatus = 2
	PayStatus_REFUNDED   PayStatus = 3
	PayStatus_PROCESSING PayStatus = 4
)

var PayStatus_name = map[int32]string{
	0: "PENDING",
	1: "SUCCESS",
	2: "FAILED",
	3: "REFUNDED",
	4: "PROCESSING",
}

var PayStatus_value = map[string]int32{
	"PENDING":    0,
	"SUCCESS":    1,
	"FAILED":     2,
	"REFUNDED":   3,
	"PROCESSING": 4,
}

func (x PayStatus) String() string {
	return proto.EnumName(PayStatus_name, int32(x))
}

type PayRequest struct {
	OrderId             string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount              float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency            string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Subject             string   `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	PayType             PayType  `protobuf:"varint,5,opt,name=pay_type,json=payType,proto3,enum=pay.PayType" json:"pay_type,omitempty"`
	NotifyUrl           string   `protobuf:"bytes,6,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReturnUrl           string   `protobuf:"bytes,7,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	ClientIp            string   `protobuf:"bytes,8,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Description         string   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayRequest) Reset()         { *m = PayRequest{} }
func (m *PayRequest) String() string { return proto.CompactTextString(m) }
func (*PayRequest) ProtoMessage()    {}

type PayResponse struct {
	PayId               string    `protobuf:"bytes,1,opt,name=pay_id,json=payId,proto3" json:"pay_id,omitempty"`
	OrderId             string    `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status              PayStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pay.PayStatus" json:"status,omitempty"`
	Amount              float64   `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PayUrl              string    `protobuf:"bytes,5,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	CodeUrl             string    `protobuf:"bytes,6,opt,name=code_url,json=codeUrl,proto3" json:"code_url,omitempty"`
	TimeExpire          string    `protobuf:"bytes,7,opt,name=time_expire,json=timeExpire,proto3" json:"time_expire,omitempty"`
	TimeCreated         string    `protobuf:"bytes,8,opt,name=time_created,json=timeCreated,proto3" json:"time_created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayResponse) Reset()         { *m = PayResponse{} }
func (m *PayResponse) String() string { return proto.CompactTextString(m) }
func (*PayResponse) ProtoMessage()    {}

type PayQuery struct {
	PayId               string   `protobuf:"bytes,1,opt,name=pay_id,json=payId,proto3" json:"pay_id,omitempty"`
	OrderId             string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayQuery) Reset()         { *m = PayQuery{} }
func (m *PayQuery) String() string { return proto.CompactTextString(m) }
func (*PayQuery) ProtoMessage()    {}

type RefundRequest struct {
	PayId               string   `protobuf:"bytes,1,opt,name=pay_id,json=payId,proto3" json:"pay_id,omitempty"`
	OrderId             string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RefundAmount        float64  `protobuf:"fixed64,3,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	RefundReason        string   `protobuf:"bytes,4,opt,name=refund_reason,json=refundReason,proto3" json:"refund_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundRequest) Reset()         { *m = RefundRequest{} }
func (m *RefundRequest) String() string { return proto.CompactTextString(m) }
func (*RefundRequest) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("pay.PayType", PayType_name, PayType_value)
	proto.RegisterEnum("pay.PayStatus", PayStatus_name, PayStatus_value)
	proto.RegisterType((*PayRequest)(nil), "pay.PayRequest")
	proto.RegisterType((*PayResponse)(nil), "pay.PayResponse")
	proto.RegisterType((*PayQuery)(nil), "pay.PayQuery")
	proto.RegisterType((*RefundRequest)(nil), "pay.RefundRequest")
}